version: "3.9"

services:
  app:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_***REMOVED***: example
      DB_NAME: mydatabase

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_***REMOVED***: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
